# This file contains the pre-commits hooks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Global settings
fail_fast: true

# From here define repos for tools involved in pre-commit
repos:

# Base plugins from pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

# Poetry plugin for pyproject.toml and poetry.lock coherency check
- repo: local
  hooks:
    - id: poetry-check
      name: poetry-check
      entry: "poetry check"
      language: system
      pass_filenames: false
    - id: poetry-lock
      name: poetry-lock
      entry: "poetry lock"
      language: system
      pass_filenames: false

# Black plugin for code format
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      files: \.py$
      args: ['--line-length=120', '-v']

# reorder-python-imports plugin
- repo: local
  hooks:
    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [python]
      files: \.py$
      args: ['--py39-plus']

# Flake8 plugin to check python syntax errors and code style
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      files: \.py$
      args: [
            '--max-line-length=120',
            '--max-doc-length=120',
            '--disable-noqa',
            '--jobs=4',
            '--indent-size=4',
            '--show-source',
            '--statistics',
            '--max-complexity=10',
            # W503: Line break occurred before a binary operator
            # W504: Line break occurred after a binary operator
            # D401: First line should be imperative
            '--ignore=W503, W504, D401',
            '--exclude=.git, __pycache__, *.pyc, .pytest_cache',
            '--docstring-convention=pep257'
            ]

# Pylint plugin to check python syntax errors and code style
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      files: \.py$
      args: [
            '--max-line-length=120',
            # E1101: bug in tool https://github.com/PyCQA/pylint/issues/4584
            # C0103: snake case issues to be fixed
            # R0904: Too many public methods (max=20)
            # R0902: Too many instance attributes (max=7)
            # R0801: Similar lines in 2 files
            '--disable=E1101, C0103, R0904, R0902, R0801',
            '--ignore-paths=tests, docsrc'
            ]

# PEP257 plugin to check compliance with PEP257
- repo: local
  hooks:
    - id: pep257
      name: pep257
      entry: pep257
      language: system
      types: [python]
      files: \.py$
      args: [
            '--count',
            # D203: 1 blank line required before class docstring. Also conflicts with D211.
            # D401: First line should be imperative
            '--ignore=D401,D203',
            ]
